AWSTemplateFormatVersion: 2010-09-09
Description: AZ Parameter

Parameters:
  MyKeyName:
    Description: Select the Key Name from the list
    Type: AWS::EC2::KeyPair::KeyName
  MyAvailabilityZone:
    Description: Select the AZ
    Type: String
    Default: us-east-1a
    AllowedValues:
      - us-east-1a
      - us-east-1b
      - us-east-1c
  MyInstanceType:
    Description: Select the ec2 Instance type from list
    Type: String
    default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium

Resources:
  DevEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-0f403e3180720dd7e
      InstanceType: !Ref MyInstanceType
      KeyName: !Ref MyKeyName
      Tags: 
        - Key: "Name"
          Value: "Prod"
      SecurityGroups:
        - default
        - !Ref SSHSecurityGroup
      AvailabilityZone: !Ref MyAvailabilityZone
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: My new SSH SG
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0 