AWSTemplateFormatVersion: 2010-09-09
Description: Basic EC2 INstance

Parameters:
  MyKeyName:
    Description: Select the Key Name from the list
    Type: AWS::EC2::KeyPair::KeyName


Resources:
  DevEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-0f403e3180720dd7e
      InstanceType: t2.micro
      KeyName: !Ref MyKeyName
      Tags: 
        - Key: "Name"
          Value: "Prod"
      SecurityGroups:
        - default
        - !Ref SSHSecurityGroup
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: My new SSH SG
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0 
